#undef _IS_IEC559

#undef _VEC2_NAME
#undef _VEC3_NAME
#undef _VEC4_NAME
#undef _QUAT_NAME
#undef _MAT4_NAME
#undef _FMAT4_NAME
#undef _BASE_TYPE
#undef _BASE_SUFFIX

#undef _ZERO
#undef _ONE
#undef _TWO
#undef _THREE
#undef _FOUR

#undef _FEQ
#undef _SIN
#undef _COS
#undef _TAN
#undef _ASIN
#undef _ACOS
#undef _ATAN2
#undef _SQRT
#undef _ABS
#undef _MIN
#undef _MAX

#undef _VEC2_TYPE
#undef _VEC3_TYPE
#undef _VEC4_TYPE
#undef _QUAT_TYPE
#undef _MAT4_TYPE
#undef _FMAT4_TYPE

#undef _CONCAT
#undef _LITERAL_HELPER
#undef _LITERAL
#undef _STATIC_CAST
#undef _NAME_HELPER
#undef _FUNC_VEC2
#undef _FUNC_VEC3
#undef _FUNC_VEC4
#undef _FUNC_QUAT
#undef _FUNC_MAT4

#undef _FUNC_SPEC
#undef _FUNC_CONV

#undef _FUNC_DECL
#undef _FUNC_IMPL

#undef _RESTRICTION_NONE
#undef _RESTRICTION_FLOAT
#undef _RESTRICTION_INT

#undef _VEC2_FUNC_DECL
#undef _VEC2_FUNC_IMPL
#undef _VEC2_FUNC_DECL_FLOAT_RESTRICTED
#undef _VEC2_FUNC_IMPL_FLOAT_RESTRICTED
#undef _VEC2_FUNC_DECL_INT_RESTRICTED
#undef _VEC2_FUNC_IMPL_INT_RESTRICTED

#undef _VEC3_FUNC_DECL
#undef _VEC3_FUNC_IMPL
#undef _VEC3_FUNC_DECL_FLOAT_RESTRICTED
#undef _VEC3_FUNC_IMPL_FLOAT_RESTRICTED
#undef _VEC3_FUNC_DECL_INT_RESTRICTED
#undef _VEC3_FUNC_IMPL_INT_RESTRICTED

#undef _VEC4_FUNC_DECL
#undef _VEC4_FUNC_IMPL
#undef _VEC4_FUNC_DECL_FLOAT_RESTRICTED
#undef _VEC4_FUNC_IMPL_FLOAT_RESTRICTED
#undef _VEC4_FUNC_DECL_INT_RESTRICTED
#undef _VEC4_FUNC_IMPL_INT_RESTRICTED

#undef _QUAT_FUNC_DECL
#undef _QUAT_FUNC_IMPL
#undef _QUAT_FUNC_DECL_FLOAT_RESTRICTED
#undef _QUAT_FUNC_IMPL_FLOAT_RESTRICTED
#undef _QUAT_FUNC_DECL_INT_RESTRICTED
#undef _QUAT_FUNC_IMPL_INT_RESTRICTED

#undef _MAT4_FUNC_DECL
#undef _MAT4_FUNC_IMPL
#undef _MAT4_FUNC_DECL_FLOAT_RESTRICTED
#undef _MAT4_FUNC_IMPL_FLOAT_RESTRICTED
#undef _MAT4_FUNC_DECL_INT_RESTRICTED
#undef _MAT4_FUNC_IMPL_INT_RESTRICTED

#undef LINEAR_ALGEBRA_INT
#undef LINEAR_ALGEBRA_I32
#undef LINEAR_ALGEBRA_I64
#undef LINEAR_ALGEBRA_FLT
#undef LINEAR_ALGEBRA_F32
#undef LINEAR_ALGEBRA_F64