#define LINEAR_ALGEBRA_F32
#define LINEAR_ALGEBRA_HEADER
#define LINEAR_ALGEBRA_VEC2_HEADER
#define LINEAR_ALGEBRA_VEC3_HEADER
#define LINEAR_ALGEBRA_VEC4_HEADER
#define LINEAR_ALGEBRA_MAT4_HEADER
#define LINEAR_ALGEBRA_QUAT_HEADER
#include "template/_vec2_float_template.h"
#define LINEAR_ALGEBRA_CLEANUP
#include "template/_vec2_float_template.h"

#define LINEAR_ALGEBRA_F32
#define LINEAR_ALGEBRA_IMPLEMENTATION
#define LINEAR_ALGEBRA_VEC2_IMPLEMENTATION
#define LINEAR_ALGEBRA_VEC3_IMPLEMENTATION
#define LINEAR_ALGEBRA_VEC4_IMPLEMENTATION
#define LINEAR_ALGEBRA_MAT4_IMPLEMENTATION
#define LINEAR_ALGEBRA_QUAT_IMPLEMENTATION
#include "template/_vec2_float_template.h"
#define LINEAR_ALGEBRA_CLEANUP
#include "template/_vec2_float_template.h"



#define LINEAR_ALGEBRA_F64
#define LINEAR_ALGEBRA_HEADER
#define LINEAR_ALGEBRA_VEC2_HEADER
#define LINEAR_ALGEBRA_VEC3_HEADER
#define LINEAR_ALGEBRA_VEC4_HEADER
#define LINEAR_ALGEBRA_MAT4_HEADER
#define LINEAR_ALGEBRA_QUAT_HEADER
#include "template/_vec2_float_template.h"
#define LINEAR_ALGEBRA_CLEANUP
#include "template/_vec2_float_template.h"

#define LINEAR_ALGEBRA_F64
#define LINEAR_ALGEBRA_IMPLEMENTATION
#define LINEAR_ALGEBRA_VEC2_IMPLEMENTATION
#define LINEAR_ALGEBRA_VEC3_IMPLEMENTATION
#define LINEAR_ALGEBRA_VEC4_IMPLEMENTATION
#define LINEAR_ALGEBRA_MAT4_IMPLEMENTATION
#define LINEAR_ALGEBRA_QUAT_IMPLEMENTATION
#include "template/_vec2_float_template.h"
#define LINEAR_ALGEBRA_CLEANUP
#include "template/_vec2_float_template.h"